# This workflow will build a Java project with Ant
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-ant

name: Java CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Download and extract NetBeans 26 ZIP distribution
      shell: bash
      run: |
        wget -q https://archive.apache.org/dist/netbeans/netbeans/26/netbeans-26-bin.zip
        wget -q https://archive.apache.org/dist/netbeans/netbeans/26/netbeans-26-bin.zip.sha512
        sha512sum -c netbeans-26-bin.zip.sha512
        unzip -q netbeans-26-bin.zip
    - name: Build with Ant
#      run: ant -noinput -buildfile build.xml build
#      run: ant -noinput -buildfile build.xml build -Dnbplatform.default.harness.dir=$GITHUB_WORKSPACE/nbmant/harness -Dnbplatform.active.dir=$GITHUB_WORKSPACE/nbmant
      run: >-
        ant -noinput -buildfile build.xml
        -Dnbplatform.default.netbeans.dest.dir=${{ github.workspace }}/netbeans
        -Dnbplatform.default.harness.dir=${{ github.workspace }}/netbeans/harness
        build